name: API PicPay Workflow Maven - DEV

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: verify branch
      run: echo "to na branch dev"
      
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1

    - name: verify version
      run: echo DEV-1${{ github.run_number }}
