name: API PicPay Workflow Maven - PROD

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: verify branch
      run: echo "to na branch PROD"
      
    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
      
    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
          image: pedrosilvanascimento/picpay-api-workflow
          tags: ${{ steps.version.outputs.previous-version }}
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
