name: API PicPay Workflow Maven - QA

on:
  push:
    branches: [ "qa" ]
  pull_request: 
    branches: [ "qa" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: verify branch
      run: echo "to na branch QA"
